"""empty message

Revision ID: 49ad12e23f46
Revises: ffef02c682d9
Create Date: 2024-01-20 22:04:59.561989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ad12e23f46'
down_revision: Union[str, None] = 'ffef02c682d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=True))
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('students', 'address',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_constraint('students_gruop_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.drop_column('students', 'gruop_id')
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('teachers', 'phone',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('teachers', 'address',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'address',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('teachers', 'phone',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('teachers', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.add_column('students', sa.Column('gruop_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_gruop_id_fkey', 'students', 'groups', ['gruop_id'], ['id'], ondelete='CASCADE')
    op.alter_column('students', 'address',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('students', 'phone',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.drop_column('students', 'group_id')
    # ### end Alembic commands ###
